#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

# Nix is broken due to timeouts, falling back to brew
packages=(
  fd
  ripgrep
  npm
  lazygit
  fzf
  kubectl
  fluxcd/tap/flux
  k9s
  direnv
)

# Iterate over the array and install each package
for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages have been installed."
