#!/bin/bash

# Set up XDG_CONFIG_HOME
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/.vim" "$HOME"/.vim
ln -sf "$PWD/.vimrc" "$HOME"/.vimrc
ln -sf "$PWD/lazygit" "$XDG_CONFIG_HOME"/lazygit

sudo mkdir /home/linuxbrew/
sudo chown $USER:users /home/linuxbrew/

NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

/home/linuxbrew/.linuxbrew/bin/brew shellenv >>~/.bashrc

packages=(
  vim
  httpyac
  lazygit
)

# Iterate over the array and install each package
for package in "${packages[@]}"; do
  echo "Installing $package..."
  /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

curl -Lo $HOME/phpactor.phar https://github.com/phpactor/phpactor/releases/latest/download/phpactor.phar
chmod a+x $HOME/phpactor.phar
mv $HOME/phpactor.phar /usr/local/bin/phpactor

echo "All packages have been installed."
