gui:
  theme:
    activeBorderColor:
      - "#B4BEFE"
      - bold
    inactiveBorderColor:
      - "#A6ADC8"
    optionsTextColor:
      - "#89B4FA"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475A"
    cherryPickedCommitFgColor:
      - "#B4BEFE"
    unstagedChangesColor:
      - "#F38BA8"
    defaultFgColor:
      - "#CDD6F4"
    searchingActiveBorderColor:
      - "#F9E2AF"
git: 
    paging:
      colorArg: always
      pager: delta --dark --paging=never --syntax-theme base16-256 -s
